# job_keywords:
#   - keyword: "machine learning engineer"
#     max_matches: 3
#   - keyword: "data scientist"
#     max_matches: 2
#   - keyword: "AI engineer"
#     max_matches: 3

# location: "United States"
# remote_only: false
# date_posted: "week"
# num_pages: 1
# max_pages: 5


# Similarity_Threshold: 0.1


# #receiver_email: "YOUR_EMAIL_WANT_TO_RECEIVE_THE_JOBS"
# receiver_email: "malmir.edumail@gmail.com"









# =========================
# JSearch Query Parameters
# =========================

query:                       # Required free-form query
  - keyword: "machine learning engineer"
    max_matches: 5
  - keyword: "data scientist"
    max_matches: 5
  - keyword: "AI engineer"
    max_matches: 5 

# page: 1                 # (optional) Start page (default = 1), we defined it the main code in the loop
num_pages: 1            # (optional) How many pages to return (max 50, default = 1)
# num_jobs: 100           # Internal control: how many jobs you want to collect in total

country: "us"           # ISO 3166-1 alpha-2 code (e.g., us, de, ca)
language: ""            # ISO 639-1 language code (e.g., en, de) or empty for default

date_posted: "today"     # Options: all, today, 3days, week, month
work_from_home: false    # Only return remote jobs (true/false)

employment_types:       # Comma-separated list: FULLTIME, CONTRACTOR, PARTTIME, INTERN
  - FULLTIME

job_requirements:       # Comma-separated list: under_3_years_experience, more_than_3_years_experience, no_experience, no_degree
  - under_3_years_experience

radius: 50              # Distance in kilometers (if query includes location)

exclude_job_publishers:   # Manually exclude specific publishers here, or use `use_blocked_employers`
  - Jobrapido
  - Jooble
  - CareerJet
  - Trovit
  - JobisJob
  - Adzuna
  - ZipRecruiter
  - Joblift
  - Monster
  - Craigslist
  - SimplyHired
  - Lensa
  - Jora
  - MyJobHelper
  - Workcircle

fields: []              # Optional: list of fields to include (e.g., employer_name, job_title). Empty returns all.

# =========================
# Filtering Controls
# =========================

use_blocked_employers: true  # If true, loads additional publishers from blocked_employers.yaml



max_pages: 5


Similarity_Threshold: 0.4









#receiver_email: "YOUR_EMAIL_WANT_TO_RECEIVE_THE_JOBS"
receiver_email: "malmir.edumail@gmail.com"
